version: '3.3'
services:

  fastapi:
      container_name: fastapi
      ports:
        - '6000:80'
      image: ghcr.io/stevenk8/apmovies:master
      volumes:
        - './APmovIes/config:/code/config'
      networks:
        - web
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fastapi-web.entrypoints=web"
        - "traefik.http.routers.fastapi-web.middlewares=redirect@file"
        - "traefik.http.routers.fastapi-secured.entrypoints=web-secured"
        - "traefik.http.routers.fastapi-secured.tls.certresolver=mytlschallenge"
        - "traefik.http.routers.fastapi-web.rule=Host(`fastapi.stevenkerautret.site`)"
        - "traefik.http.routers.fastapi-secured.rule=Host(`fastapi.stevenkerautret.site`)"

networks:
  web:
    external: true
  backend:
    external: false
